name: Building recovery

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]
    

env:
  MANIFEST: git://github.com/PitchBlackRecoveryProject/manifest_pb.git -b android-9.0
  DEVICE: sakura
  DT_LINK: https://github.com/LinuxPanda/android_recovery_xiaomi_rosy
  DT_PATH: device/xiaomi/rosy
  KERNEL_LINK: https://github.com/Pulkit077/kernel_xiaomi_rosy
  KERNEL_PATH: kernel/xiaomi/rosy
  TARGET: recoveryimage
  TZ: Asia/Kolkata

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@master
         
       - name: Initializing environment
         run: |
            sudo -E apt-get -qq update
            sudo -E apt-get -qq install bc build-essential zip curl libstdc++6 git wget python gcc clang libssl-dev repo rsync flex curl  bison aria2
            sudo curl --create-dirs -L -o /usr/local/bin/repo -O -L https://storage.googleapis.com/git-repo-downloads/repo
            sudo chmod a+rx /usr/local/bin/repo
            
       - name: Sync recovery source and device tree
         run: |
             mkdir work
             cd work
             repo init -u $MANIFEST --depth=1 --groups=all,-notdefault,-device,-darwin,-x86,-mips
             repo sync -j4
             git clone $DT_LINK --depth=1 --single-branch $DT_PATH
             git clone $KERNEL_LINK --depth=1 --single-branch $KERNEL_PATH
             
       - name: Build
         run: |
              cd work
              . build/envsetup.sh &&lunch omni_$DEVICE-eng &&export ALLOW_MISSING_DEPENDENCIES=true && mka $TARGET
             
       - name: Upload recovery image
         run: |
              cd work/out/target/product/$DEVICE
              curl -sL https://git.io/file-transfer | sh
              ./transfer bit *$DEVICE*.zip    
